# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template models.py.jinja --
from pydantic import BaseModel

from . import fields, actions
from ._types import FuncType
from ._builder import serialize_base64
from ._compat import PYDANTIC_V2, ConfigDict

if TYPE_CHECKING:
    from .client import Prisma


_PrismaModelT = TypeVar('_PrismaModelT', bound='_PrismaModel')


class _PrismaModel(BaseModel):
    if PYDANTIC_V2:
        model_config: ClassVar[ConfigDict] = ConfigDict(
            use_enum_values=True,
            arbitrary_types_allowed=True,
            populate_by_name=True,
        )
    elif not TYPE_CHECKING:
        from ._compat import BaseConfig

        class Config(BaseConfig):
            use_enum_values: bool = True
            arbitrary_types_allowed: bool = True
            allow_population_by_field_name: bool = True
            json_encoders: Dict[Any, FuncType] = {
                fields.Base64: serialize_base64,
            }

    # TODO: ensure this is required by subclasses
    __prisma_model__: ClassVar[str]


class BaseUser(_PrismaModel):
    __prisma_model__: ClassVar[Literal['User']] = 'User'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserActions[_PrismaModelT](client or get_client(), cls)


class BaseReportRequest(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ReportRequest']] = 'ReportRequest'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ReportRequestActions[_PrismaModelT]':
        from .client import get_client

        return actions.ReportRequestActions[_PrismaModelT](client or get_client(), cls)


class BaseReportSource(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ReportSource']] = 'ReportSource'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ReportSourceActions[_PrismaModelT]':
        from .client import get_client

        return actions.ReportSourceActions[_PrismaModelT](client or get_client(), cls)


class BaseVerificationToken(_PrismaModel):
    __prisma_model__: ClassVar[Literal['VerificationToken']] = 'VerificationToken'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.VerificationTokenActions[_PrismaModelT]':
        from .client import get_client

        return actions.VerificationTokenActions[_PrismaModelT](client or get_client(), cls)


class BasePasswordResetToken(_PrismaModel):
    __prisma_model__: ClassVar[Literal['PasswordResetToken']] = 'PasswordResetToken'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.PasswordResetTokenActions[_PrismaModelT]':
        from .client import get_client

        return actions.PasswordResetTokenActions[_PrismaModelT](client or get_client(), cls)


class BaseFeedback(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Feedback']] = 'Feedback'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.FeedbackActions[_PrismaModelT]':
        from .client import get_client

        return actions.FeedbackActions[_PrismaModelT](client or get_client(), cls)


class BaseUserMessage(_PrismaModel):
    __prisma_model__: ClassVar[Literal['UserMessage']] = 'UserMessage'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserMessageActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserMessageActions[_PrismaModelT](client or get_client(), cls)


class BaseAdminAuditLog(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AdminAuditLog']] = 'AdminAuditLog'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AdminAuditLogActions[_PrismaModelT]':
        from .client import get_client

        return actions.AdminAuditLogActions[_PrismaModelT](client or get_client(), cls)


class BaseWatchedCompany(_PrismaModel):
    __prisma_model__: ClassVar[Literal['WatchedCompany']] = 'WatchedCompany'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.WatchedCompanyActions[_PrismaModelT]':
        from .client import get_client

        return actions.WatchedCompanyActions[_PrismaModelT](client or get_client(), cls)


class BaseAlertEvent(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AlertEvent']] = 'AlertEvent'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AlertEventActions[_PrismaModelT]':
        from .client import get_client

        return actions.AlertEventActions[_PrismaModelT](client or get_client(), cls)


class BaseAlertDelivery(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AlertDelivery']] = 'AlertDelivery'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AlertDeliveryActions[_PrismaModelT]':
        from .client import get_client

        return actions.AlertDeliveryActions[_PrismaModelT](client or get_client(), cls)


class BaseCompany(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Company']] = 'Company'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CompanyActions[_PrismaModelT]':
        from .client import get_client

        return actions.CompanyActions[_PrismaModelT](client or get_client(), cls)


class BaseCompanyPerson(_PrismaModel):
    __prisma_model__: ClassVar[Literal['CompanyPerson']] = 'CompanyPerson'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CompanyPersonActions[_PrismaModelT]':
        from .client import get_client

        return actions.CompanyPersonActions[_PrismaModelT](client or get_client(), cls)


class BaseNaceCode(_PrismaModel):
    __prisma_model__: ClassVar[Literal['NaceCode']] = 'NaceCode'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.NaceCodeActions[_PrismaModelT]':
        from .client import get_client

        return actions.NaceCodeActions[_PrismaModelT](client or get_client(), cls)


class BaseCompanyEvent(_PrismaModel):
    __prisma_model__: ClassVar[Literal['CompanyEvent']] = 'CompanyEvent'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CompanyEventActions[_PrismaModelT]':
        from .client import get_client

        return actions.CompanyEventActions[_PrismaModelT](client or get_client(), cls)


class BaseVestnikEvent(_PrismaModel):
    __prisma_model__: ClassVar[Literal['VestnikEvent']] = 'VestnikEvent'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.VestnikEventActions[_PrismaModelT]':
        from .client import get_client

        return actions.VestnikEventActions[_PrismaModelT](client or get_client(), cls)


class BaseFinancialStatement(_PrismaModel):
    __prisma_model__: ClassVar[Literal['FinancialStatement']] = 'FinancialStatement'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.FinancialStatementActions[_PrismaModelT]':
        from .client import get_client

        return actions.FinancialStatementActions[_PrismaModelT](client or get_client(), cls)


class BaseAuditorOpinion(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AuditorOpinion']] = 'AuditorOpinion'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AuditorOpinionActions[_PrismaModelT]':
        from .client import get_client

        return actions.AuditorOpinionActions[_PrismaModelT](client or get_client(), cls)


class BaseNarrativeRiskAnalysis(_PrismaModel):
    __prisma_model__: ClassVar[Literal['NarrativeRiskAnalysis']] = 'NarrativeRiskAnalysis'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.NarrativeRiskAnalysisActions[_PrismaModelT]':
        from .client import get_client

        return actions.NarrativeRiskAnalysisActions[_PrismaModelT](client or get_client(), cls)


class BaseNotesRiskAnalysis(_PrismaModel):
    __prisma_model__: ClassVar[Literal['NotesRiskAnalysis']] = 'NotesRiskAnalysis'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.NotesRiskAnalysisActions[_PrismaModelT]':
        from .client import get_client

        return actions.NotesRiskAnalysisActions[_PrismaModelT](client or get_client(), cls)


class BaseAuditVerdict(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AuditVerdict']] = 'AuditVerdict'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AuditVerdictActions[_PrismaModelT]':
        from .client import get_client

        return actions.AuditVerdictActions[_PrismaModelT](client or get_client(), cls)


class BaseScoringSnapshot(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ScoringSnapshot']] = 'ScoringSnapshot'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ScoringSnapshotActions[_PrismaModelT]':
        from .client import get_client

        return actions.ScoringSnapshotActions[_PrismaModelT](client or get_client(), cls)


class BaseCreditBatch(_PrismaModel):
    __prisma_model__: ClassVar[Literal['CreditBatch']] = 'CreditBatch'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CreditBatchActions[_PrismaModelT]':
        from .client import get_client

        return actions.CreditBatchActions[_PrismaModelT](client or get_client(), cls)


class BaseWallet(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Wallet']] = 'Wallet'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.WalletActions[_PrismaModelT]':
        from .client import get_client

        return actions.WalletActions[_PrismaModelT](client or get_client(), cls)


class BaseWalletTransaction(_PrismaModel):
    __prisma_model__: ClassVar[Literal['WalletTransaction']] = 'WalletTransaction'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.WalletTransactionActions[_PrismaModelT]':
        from .client import get_client

        return actions.WalletTransactionActions[_PrismaModelT](client or get_client(), cls)


