# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off
from __future__ import annotations

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template client.py.jinja --
import warnings
import logging
from datetime import timedelta
from pathlib import Path
from types import TracebackType
from typing_extensions import override

from pydantic import BaseModel

from . import types, models, errors, actions
from ._base_client import BasePrisma, UseClientDefault, USE_CLIENT_DEFAULT
from .types import DatasourceOverride, HttpConfig, MetricsFormat
from ._types import BaseModelT, PrismaMethod, TransactionId, Datasource
from .bases import _PrismaModel
from ._builder import QueryBuilder, dumps
from .generator.models import EngineType, OptionalValueFromEnvVar, BinaryPaths
from ._compat import removeprefix, model_parse
from ._constants import CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED, DEFAULT_CONNECT_TIMEOUT, DEFAULT_TX_MAX_WAIT, DEFAULT_TX_TIMEOUT
from ._raw_query import deserialize_raw_results
from ._metrics import Metrics
from .metadata import PRISMA_MODELS, RELATIONAL_FIELD_MAPPINGS
from ._transactions import AsyncTransactionManager, SyncTransactionManager

# re-exports
from ._base_client import SyncBasePrisma, AsyncBasePrisma, load_env as load_env
from ._registry import (
    register as register,
    get_client as get_client,
    RegisteredClient as RegisteredClient,
)


__all__ = (
    'ENGINE_TYPE',
    'SCHEMA_PATH',
    'BINARY_PATHS',
    'Batch',
    'Prisma',
    'Client',
    'load_env',
    'register',
    'get_client',
)

log: logging.Logger = logging.getLogger(__name__)

SCHEMA_PATH = Path('/Users/dusanbaran/Desktop/Projects/scripta/worker/schema.prisma')
PACKAGED_SCHEMA_PATH = Path(__file__).parent.joinpath('schema.prisma')
ENGINE_TYPE: EngineType = EngineType.binary
BINARY_PATHS = model_parse(BinaryPaths, {'queryEngine': {'darwin-arm64': '/Users/dusanbaran/Desktop/Projects/scripta/node_modules/prisma/query-engine-darwin-arm64'}, 'introspectionEngine': {}, 'migrationEngine': {}, 'libqueryEngine': {}, 'prismaFmt': {}})


class Prisma(AsyncBasePrisma):
    # Note: these property names can be customised using `/// @Python(instance_name: '...')`
    # https://prisma-client-py.readthedocs.io/en/stable/reference/schema-extensions/#instance_name
    user: 'actions.UserActions[models.User]'
    reportrequest: 'actions.ReportRequestActions[models.ReportRequest]'
    reportsource: 'actions.ReportSourceActions[models.ReportSource]'
    verificationtoken: 'actions.VerificationTokenActions[models.VerificationToken]'
    passwordresettoken: 'actions.PasswordResetTokenActions[models.PasswordResetToken]'
    feedback: 'actions.FeedbackActions[models.Feedback]'
    usermessage: 'actions.UserMessageActions[models.UserMessage]'
    adminauditlog: 'actions.AdminAuditLogActions[models.AdminAuditLog]'
    watchedcompany: 'actions.WatchedCompanyActions[models.WatchedCompany]'
    alertevent: 'actions.AlertEventActions[models.AlertEvent]'
    alertdelivery: 'actions.AlertDeliveryActions[models.AlertDelivery]'
    company: 'actions.CompanyActions[models.Company]'
    companyperson: 'actions.CompanyPersonActions[models.CompanyPerson]'
    nacecode: 'actions.NaceCodeActions[models.NaceCode]'
    companyevent: 'actions.CompanyEventActions[models.CompanyEvent]'
    vestnikevent: 'actions.VestnikEventActions[models.VestnikEvent]'
    financialstatement: 'actions.FinancialStatementActions[models.FinancialStatement]'
    auditoropinion: 'actions.AuditorOpinionActions[models.AuditorOpinion]'
    narrativeriskanalysis: 'actions.NarrativeRiskAnalysisActions[models.NarrativeRiskAnalysis]'
    notesriskanalysis: 'actions.NotesRiskAnalysisActions[models.NotesRiskAnalysis]'
    auditverdict: 'actions.AuditVerdictActions[models.AuditVerdict]'
    scoringsnapshot: 'actions.ScoringSnapshotActions[models.ScoringSnapshot]'
    creditbatch: 'actions.CreditBatchActions[models.CreditBatch]'
    wallet: 'actions.WalletActions[models.Wallet]'
    wallettransaction: 'actions.WalletTransactionActions[models.WalletTransaction]'

    __slots__ = (
        'user',
        'reportrequest',
        'reportsource',
        'verificationtoken',
        'passwordresettoken',
        'feedback',
        'usermessage',
        'adminauditlog',
        'watchedcompany',
        'alertevent',
        'alertdelivery',
        'company',
        'companyperson',
        'nacecode',
        'companyevent',
        'vestnikevent',
        'financialstatement',
        'auditoropinion',
        'narrativeriskanalysis',
        'notesriskanalysis',
        'auditverdict',
        'scoringsnapshot',
        'creditbatch',
        'wallet',
        'wallettransaction',
    )

    def __init__(
        self,
        *,
        use_dotenv: bool = True,
        log_queries: bool = False,
        auto_register: bool = False,
        datasource: DatasourceOverride | None = None,
        connect_timeout: int | timedelta = DEFAULT_CONNECT_TIMEOUT,
        http: HttpConfig | None = None,
    ) -> None:
        super().__init__(
            http=http,
            use_dotenv=use_dotenv,
            log_queries=log_queries,
            datasource=datasource,
            connect_timeout=connect_timeout,
        )
        self._set_generated_properties(
            schema_path=SCHEMA_PATH,
            engine_type=ENGINE_TYPE,
            prisma_models=PRISMA_MODELS,
            packaged_schema_path=PACKAGED_SCHEMA_PATH,
            relational_field_mappings=RELATIONAL_FIELD_MAPPINGS,
            preview_features=set([]),
            active_provider='postgresql',
            default_datasource_name='db',
        )

        self.user = actions.UserActions[models.User](self, models.User)
        self.reportrequest = actions.ReportRequestActions[models.ReportRequest](self, models.ReportRequest)
        self.reportsource = actions.ReportSourceActions[models.ReportSource](self, models.ReportSource)
        self.verificationtoken = actions.VerificationTokenActions[models.VerificationToken](self, models.VerificationToken)
        self.passwordresettoken = actions.PasswordResetTokenActions[models.PasswordResetToken](self, models.PasswordResetToken)
        self.feedback = actions.FeedbackActions[models.Feedback](self, models.Feedback)
        self.usermessage = actions.UserMessageActions[models.UserMessage](self, models.UserMessage)
        self.adminauditlog = actions.AdminAuditLogActions[models.AdminAuditLog](self, models.AdminAuditLog)
        self.watchedcompany = actions.WatchedCompanyActions[models.WatchedCompany](self, models.WatchedCompany)
        self.alertevent = actions.AlertEventActions[models.AlertEvent](self, models.AlertEvent)
        self.alertdelivery = actions.AlertDeliveryActions[models.AlertDelivery](self, models.AlertDelivery)
        self.company = actions.CompanyActions[models.Company](self, models.Company)
        self.companyperson = actions.CompanyPersonActions[models.CompanyPerson](self, models.CompanyPerson)
        self.nacecode = actions.NaceCodeActions[models.NaceCode](self, models.NaceCode)
        self.companyevent = actions.CompanyEventActions[models.CompanyEvent](self, models.CompanyEvent)
        self.vestnikevent = actions.VestnikEventActions[models.VestnikEvent](self, models.VestnikEvent)
        self.financialstatement = actions.FinancialStatementActions[models.FinancialStatement](self, models.FinancialStatement)
        self.auditoropinion = actions.AuditorOpinionActions[models.AuditorOpinion](self, models.AuditorOpinion)
        self.narrativeriskanalysis = actions.NarrativeRiskAnalysisActions[models.NarrativeRiskAnalysis](self, models.NarrativeRiskAnalysis)
        self.notesriskanalysis = actions.NotesRiskAnalysisActions[models.NotesRiskAnalysis](self, models.NotesRiskAnalysis)
        self.auditverdict = actions.AuditVerdictActions[models.AuditVerdict](self, models.AuditVerdict)
        self.scoringsnapshot = actions.ScoringSnapshotActions[models.ScoringSnapshot](self, models.ScoringSnapshot)
        self.creditbatch = actions.CreditBatchActions[models.CreditBatch](self, models.CreditBatch)
        self.wallet = actions.WalletActions[models.Wallet](self, models.Wallet)
        self.wallettransaction = actions.WalletTransactionActions[models.WalletTransaction](self, models.WalletTransaction)

        if auto_register:
            register(self)

    @property
    @override
    def _default_datasource(self) -> Datasource:
        return {
            'name': 'db',
            'url': OptionalValueFromEnvVar(**{'value': None, 'fromEnvVar': 'DATABASE_URL'}).resolve(),
            'source_file_path': '/Users/dusanbaran/Desktop/Projects/scripta/worker/schema.prisma',
        }

    async def execute_raw(self, query: LiteralString, *args: Any) -> int:
        resp = await self._execute(
            method='execute_raw',
            arguments={
                'query': query,
                'parameters': args,
            },
            model=None,
        )
        return int(resp['data']['result'])

    @overload
    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
    ) -> dict[str, Any]:
        ...

    @overload
    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
        model: Type[BaseModelT],
    ) -> Optional[BaseModelT]:
        ...

    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
        model: Optional[Type[BaseModelT]] = None,
    ) -> Union[Optional[BaseModelT], dict[str, Any]]:
        """This function is the exact same as `query_raw()` but returns the first result.

        If model is given, the returned record is converted to the pydantic model first,
        otherwise a raw dictionary will be returned.
        """
        results: Sequence[Union[BaseModelT, dict[str, Any]]]
        if model is not None:
            results = await self.query_raw(query, *args, model=model)
        else:
            results = await self.query_raw(query, *args)

        if not results:
            return None

        return results[0]

    @overload
    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
    ) -> List[dict[str, Any]]:
        ...

    @overload
    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
        model: Type[BaseModelT],
    ) -> List[BaseModelT]:
        ...

    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
        model: Optional[Type[BaseModelT]] = None,
    ) -> Union[List[BaseModelT], List[dict[str, Any]]]:
        """Execute a raw SQL query against the database.

        If model is given, each returned record is converted to the pydantic model first,
        otherwise results will be raw dictionaries.
        """
        resp = await self._execute(
            method='query_raw',
            arguments={
                'query': query,
                'parameters': args,
            },
            model=model,
        )
        result = resp['data']['result']
        if model is not None:
            return deserialize_raw_results(result, model=model)

        return deserialize_raw_results(result)

    def batch_(self) -> Batch:
        """Returns a context manager for grouping write queries into a single transaction."""
        return Batch(client=self)

    def tx(
        self,
        *,
        max_wait: Union[int, timedelta] = DEFAULT_TX_MAX_WAIT,
        timeout: Union[int, timedelta] = DEFAULT_TX_TIMEOUT,
    ) -> TransactionManager:
        """Returns a context manager for executing queries within a database transaction.

        Entering the context manager returns a new Prisma instance wrapping all
        actions within a transaction, queries will be isolated to the Prisma instance and
        will not be commited to the database until the context manager exits.

        By default, Prisma will wait a maximum of 2 seconds to acquire a transaction from the database. You can modify this
        default with the `max_wait` argument which accepts a value in milliseconds or `datetime.timedelta`.

        By default, Prisma will cancel and rollback ay transactions that last longer than 5 seconds. You can modify this timeout
        with the `timeout` argument which accepts a value in milliseconds or `datetime.timedelta`.

        Example usage:

        ```py
        async with client.tx() as transaction:
            user1 = await client.user.create({'name': 'Robert'})
            user2 = await client.user.create({'name': 'Tegan'})
        ```

        In the above example, if the first database call succeeds but the second does not then neither of the records will be created.
        """
        return TransactionManager(
            client=self,
            max_wait=max_wait,
            timeout=timeout,
        )


TransactionManager = AsyncTransactionManager[Prisma]


# TODO: this should return the results as well
# TODO: don't require copy-pasting arguments between actions and batch actions
class Batch:
    user: 'UserBatchActions'
    reportrequest: 'ReportRequestBatchActions'
    reportsource: 'ReportSourceBatchActions'
    verificationtoken: 'VerificationTokenBatchActions'
    passwordresettoken: 'PasswordResetTokenBatchActions'
    feedback: 'FeedbackBatchActions'
    usermessage: 'UserMessageBatchActions'
    adminauditlog: 'AdminAuditLogBatchActions'
    watchedcompany: 'WatchedCompanyBatchActions'
    alertevent: 'AlertEventBatchActions'
    alertdelivery: 'AlertDeliveryBatchActions'
    company: 'CompanyBatchActions'
    companyperson: 'CompanyPersonBatchActions'
    nacecode: 'NaceCodeBatchActions'
    companyevent: 'CompanyEventBatchActions'
    vestnikevent: 'VestnikEventBatchActions'
    financialstatement: 'FinancialStatementBatchActions'
    auditoropinion: 'AuditorOpinionBatchActions'
    narrativeriskanalysis: 'NarrativeRiskAnalysisBatchActions'
    notesriskanalysis: 'NotesRiskAnalysisBatchActions'
    auditverdict: 'AuditVerdictBatchActions'
    scoringsnapshot: 'ScoringSnapshotBatchActions'
    creditbatch: 'CreditBatchBatchActions'
    wallet: 'WalletBatchActions'
    wallettransaction: 'WalletTransactionBatchActions'

    def __init__(self, client: Prisma) -> None:
        self.__client = client
        self.__queries: List[str] = []
        self._active_provider = client._active_provider
        self.user = UserBatchActions(self)
        self.reportrequest = ReportRequestBatchActions(self)
        self.reportsource = ReportSourceBatchActions(self)
        self.verificationtoken = VerificationTokenBatchActions(self)
        self.passwordresettoken = PasswordResetTokenBatchActions(self)
        self.feedback = FeedbackBatchActions(self)
        self.usermessage = UserMessageBatchActions(self)
        self.adminauditlog = AdminAuditLogBatchActions(self)
        self.watchedcompany = WatchedCompanyBatchActions(self)
        self.alertevent = AlertEventBatchActions(self)
        self.alertdelivery = AlertDeliveryBatchActions(self)
        self.company = CompanyBatchActions(self)
        self.companyperson = CompanyPersonBatchActions(self)
        self.nacecode = NaceCodeBatchActions(self)
        self.companyevent = CompanyEventBatchActions(self)
        self.vestnikevent = VestnikEventBatchActions(self)
        self.financialstatement = FinancialStatementBatchActions(self)
        self.auditoropinion = AuditorOpinionBatchActions(self)
        self.narrativeriskanalysis = NarrativeRiskAnalysisBatchActions(self)
        self.notesriskanalysis = NotesRiskAnalysisBatchActions(self)
        self.auditverdict = AuditVerdictBatchActions(self)
        self.scoringsnapshot = ScoringSnapshotBatchActions(self)
        self.creditbatch = CreditBatchBatchActions(self)
        self.wallet = WalletBatchActions(self)
        self.wallettransaction = WalletTransactionBatchActions(self)

    def _add(self, **kwargs: Any) -> None:
        builder = QueryBuilder(
            **kwargs,
            prisma_models=PRISMA_MODELS,
            relational_field_mappings=RELATIONAL_FIELD_MAPPINGS,
        )
        self.__queries.append(builder.build_query())

    async def commit(self) -> None:
        """Execute the queries"""
        # TODO: normalise this, we should still call client._execute
        queries = self.__queries
        self.__queries = []

        payload = {
            'batch': [
                {
                    'query': query,
                    'variables': {},
                }
                for query in queries
            ],
            'transaction': True,
        }
        await self.__client._engine.query(
            dumps(payload),
            tx_id=self.__client._tx_id,
        )

    def execute_raw(self, query: LiteralString, *args: Any) -> None:
        self._add(
            method='execute_raw',
            arguments={
                'query': query,
                'parameters': args,
            }
        )

    async def __aenter__(self) -> 'Batch':
        return self

    async def __aexit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc: Optional[BaseException],
        exc_tb: Optional[TracebackType],
    ) -> None:
        if exc is None:
            await self.commit()


# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class UserBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.UserCreateInput,
        include: Optional[types.UserInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.User,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.UserCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.User,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.UserWhereUniqueInput,
        include: Optional[types.UserInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.User,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.UserUpdateInput,
        where: types.UserWhereUniqueInput,
        include: Optional[types.UserInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.User,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.UserWhereUniqueInput,
        data: types.UserUpsertInput,
        include: Optional[types.UserInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.User,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.UserUpdateManyMutationInput,
        where: types.UserWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.User,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.UserWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.User,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class ReportRequestBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.ReportRequestCreateInput,
        include: Optional[types.ReportRequestInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.ReportRequest,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.ReportRequestCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.ReportRequest,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.ReportRequestWhereUniqueInput,
        include: Optional[types.ReportRequestInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.ReportRequest,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.ReportRequestUpdateInput,
        where: types.ReportRequestWhereUniqueInput,
        include: Optional[types.ReportRequestInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.ReportRequest,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.ReportRequestWhereUniqueInput,
        data: types.ReportRequestUpsertInput,
        include: Optional[types.ReportRequestInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.ReportRequest,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.ReportRequestUpdateManyMutationInput,
        where: types.ReportRequestWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.ReportRequest,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.ReportRequestWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.ReportRequest,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class ReportSourceBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.ReportSourceCreateInput,
        include: Optional[types.ReportSourceInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.ReportSource,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.ReportSourceCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.ReportSource,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.ReportSourceWhereUniqueInput,
        include: Optional[types.ReportSourceInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.ReportSource,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.ReportSourceUpdateInput,
        where: types.ReportSourceWhereUniqueInput,
        include: Optional[types.ReportSourceInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.ReportSource,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.ReportSourceWhereUniqueInput,
        data: types.ReportSourceUpsertInput,
        include: Optional[types.ReportSourceInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.ReportSource,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.ReportSourceUpdateManyMutationInput,
        where: types.ReportSourceWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.ReportSource,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.ReportSourceWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.ReportSource,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class VerificationTokenBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.VerificationTokenCreateInput,
        include: Optional[types.VerificationTokenInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.VerificationToken,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.VerificationTokenCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.VerificationToken,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.VerificationTokenWhereUniqueInput,
        include: Optional[types.VerificationTokenInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.VerificationToken,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.VerificationTokenUpdateInput,
        where: types.VerificationTokenWhereUniqueInput,
        include: Optional[types.VerificationTokenInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.VerificationToken,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.VerificationTokenWhereUniqueInput,
        data: types.VerificationTokenUpsertInput,
        include: Optional[types.VerificationTokenInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.VerificationToken,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.VerificationTokenUpdateManyMutationInput,
        where: types.VerificationTokenWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.VerificationToken,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.VerificationTokenWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.VerificationToken,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class PasswordResetTokenBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.PasswordResetTokenCreateInput,
        include: Optional[types.PasswordResetTokenInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.PasswordResetToken,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.PasswordResetTokenCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.PasswordResetToken,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.PasswordResetTokenWhereUniqueInput,
        include: Optional[types.PasswordResetTokenInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.PasswordResetToken,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.PasswordResetTokenUpdateInput,
        where: types.PasswordResetTokenWhereUniqueInput,
        include: Optional[types.PasswordResetTokenInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.PasswordResetToken,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.PasswordResetTokenWhereUniqueInput,
        data: types.PasswordResetTokenUpsertInput,
        include: Optional[types.PasswordResetTokenInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.PasswordResetToken,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.PasswordResetTokenUpdateManyMutationInput,
        where: types.PasswordResetTokenWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.PasswordResetToken,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.PasswordResetTokenWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.PasswordResetToken,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class FeedbackBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.FeedbackCreateInput,
        include: Optional[types.FeedbackInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Feedback,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.FeedbackCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Feedback,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.FeedbackWhereUniqueInput,
        include: Optional[types.FeedbackInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Feedback,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.FeedbackUpdateInput,
        where: types.FeedbackWhereUniqueInput,
        include: Optional[types.FeedbackInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Feedback,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.FeedbackWhereUniqueInput,
        data: types.FeedbackUpsertInput,
        include: Optional[types.FeedbackInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Feedback,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.FeedbackUpdateManyMutationInput,
        where: types.FeedbackWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Feedback,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.FeedbackWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Feedback,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class UserMessageBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.UserMessageCreateInput,
        include: Optional[types.UserMessageInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.UserMessage,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.UserMessageCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.UserMessage,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.UserMessageWhereUniqueInput,
        include: Optional[types.UserMessageInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.UserMessage,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.UserMessageUpdateInput,
        where: types.UserMessageWhereUniqueInput,
        include: Optional[types.UserMessageInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.UserMessage,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.UserMessageWhereUniqueInput,
        data: types.UserMessageUpsertInput,
        include: Optional[types.UserMessageInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.UserMessage,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.UserMessageUpdateManyMutationInput,
        where: types.UserMessageWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.UserMessage,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.UserMessageWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.UserMessage,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class AdminAuditLogBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.AdminAuditLogCreateInput,
        include: Optional[types.AdminAuditLogInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.AdminAuditLog,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.AdminAuditLogCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.AdminAuditLog,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.AdminAuditLogWhereUniqueInput,
        include: Optional[types.AdminAuditLogInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.AdminAuditLog,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.AdminAuditLogUpdateInput,
        where: types.AdminAuditLogWhereUniqueInput,
        include: Optional[types.AdminAuditLogInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.AdminAuditLog,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.AdminAuditLogWhereUniqueInput,
        data: types.AdminAuditLogUpsertInput,
        include: Optional[types.AdminAuditLogInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.AdminAuditLog,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.AdminAuditLogUpdateManyMutationInput,
        where: types.AdminAuditLogWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.AdminAuditLog,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.AdminAuditLogWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.AdminAuditLog,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class WatchedCompanyBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.WatchedCompanyCreateInput,
        include: Optional[types.WatchedCompanyInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.WatchedCompany,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.WatchedCompanyCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.WatchedCompany,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.WatchedCompanyWhereUniqueInput,
        include: Optional[types.WatchedCompanyInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.WatchedCompany,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.WatchedCompanyUpdateInput,
        where: types.WatchedCompanyWhereUniqueInput,
        include: Optional[types.WatchedCompanyInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.WatchedCompany,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.WatchedCompanyWhereUniqueInput,
        data: types.WatchedCompanyUpsertInput,
        include: Optional[types.WatchedCompanyInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.WatchedCompany,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.WatchedCompanyUpdateManyMutationInput,
        where: types.WatchedCompanyWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.WatchedCompany,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.WatchedCompanyWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.WatchedCompany,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class AlertEventBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.AlertEventCreateInput,
        include: Optional[types.AlertEventInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.AlertEvent,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.AlertEventCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.AlertEvent,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.AlertEventWhereUniqueInput,
        include: Optional[types.AlertEventInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.AlertEvent,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.AlertEventUpdateInput,
        where: types.AlertEventWhereUniqueInput,
        include: Optional[types.AlertEventInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.AlertEvent,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.AlertEventWhereUniqueInput,
        data: types.AlertEventUpsertInput,
        include: Optional[types.AlertEventInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.AlertEvent,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.AlertEventUpdateManyMutationInput,
        where: types.AlertEventWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.AlertEvent,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.AlertEventWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.AlertEvent,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class AlertDeliveryBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.AlertDeliveryCreateInput,
        include: Optional[types.AlertDeliveryInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.AlertDelivery,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.AlertDeliveryCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.AlertDelivery,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.AlertDeliveryWhereUniqueInput,
        include: Optional[types.AlertDeliveryInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.AlertDelivery,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.AlertDeliveryUpdateInput,
        where: types.AlertDeliveryWhereUniqueInput,
        include: Optional[types.AlertDeliveryInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.AlertDelivery,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.AlertDeliveryWhereUniqueInput,
        data: types.AlertDeliveryUpsertInput,
        include: Optional[types.AlertDeliveryInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.AlertDelivery,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.AlertDeliveryUpdateManyMutationInput,
        where: types.AlertDeliveryWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.AlertDelivery,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.AlertDeliveryWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.AlertDelivery,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class CompanyBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.CompanyCreateInput,
        include: Optional[types.CompanyInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Company,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.CompanyCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Company,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.CompanyWhereUniqueInput,
        include: Optional[types.CompanyInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Company,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.CompanyUpdateInput,
        where: types.CompanyWhereUniqueInput,
        include: Optional[types.CompanyInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Company,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.CompanyWhereUniqueInput,
        data: types.CompanyUpsertInput,
        include: Optional[types.CompanyInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Company,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.CompanyUpdateManyMutationInput,
        where: types.CompanyWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Company,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.CompanyWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Company,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class CompanyPersonBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.CompanyPersonCreateInput,
        include: Optional[types.CompanyPersonInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.CompanyPerson,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.CompanyPersonCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.CompanyPerson,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.CompanyPersonWhereUniqueInput,
        include: Optional[types.CompanyPersonInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.CompanyPerson,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.CompanyPersonUpdateInput,
        where: types.CompanyPersonWhereUniqueInput,
        include: Optional[types.CompanyPersonInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.CompanyPerson,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.CompanyPersonWhereUniqueInput,
        data: types.CompanyPersonUpsertInput,
        include: Optional[types.CompanyPersonInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.CompanyPerson,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.CompanyPersonUpdateManyMutationInput,
        where: types.CompanyPersonWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.CompanyPerson,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.CompanyPersonWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.CompanyPerson,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class NaceCodeBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.NaceCodeCreateInput,
        include: Optional[types.NaceCodeInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.NaceCode,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.NaceCodeCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.NaceCode,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.NaceCodeWhereUniqueInput,
        include: Optional[types.NaceCodeInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.NaceCode,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.NaceCodeUpdateInput,
        where: types.NaceCodeWhereUniqueInput,
        include: Optional[types.NaceCodeInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.NaceCode,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.NaceCodeWhereUniqueInput,
        data: types.NaceCodeUpsertInput,
        include: Optional[types.NaceCodeInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.NaceCode,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.NaceCodeUpdateManyMutationInput,
        where: types.NaceCodeWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.NaceCode,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.NaceCodeWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.NaceCode,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class CompanyEventBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.CompanyEventCreateInput,
        include: Optional[types.CompanyEventInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.CompanyEvent,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.CompanyEventCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.CompanyEvent,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.CompanyEventWhereUniqueInput,
        include: Optional[types.CompanyEventInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.CompanyEvent,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.CompanyEventUpdateInput,
        where: types.CompanyEventWhereUniqueInput,
        include: Optional[types.CompanyEventInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.CompanyEvent,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.CompanyEventWhereUniqueInput,
        data: types.CompanyEventUpsertInput,
        include: Optional[types.CompanyEventInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.CompanyEvent,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.CompanyEventUpdateManyMutationInput,
        where: types.CompanyEventWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.CompanyEvent,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.CompanyEventWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.CompanyEvent,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class VestnikEventBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.VestnikEventCreateInput,
        include: Optional[types.VestnikEventInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.VestnikEvent,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.VestnikEventCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.VestnikEvent,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.VestnikEventWhereUniqueInput,
        include: Optional[types.VestnikEventInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.VestnikEvent,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.VestnikEventUpdateInput,
        where: types.VestnikEventWhereUniqueInput,
        include: Optional[types.VestnikEventInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.VestnikEvent,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.VestnikEventWhereUniqueInput,
        data: types.VestnikEventUpsertInput,
        include: Optional[types.VestnikEventInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.VestnikEvent,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.VestnikEventUpdateManyMutationInput,
        where: types.VestnikEventWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.VestnikEvent,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.VestnikEventWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.VestnikEvent,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class FinancialStatementBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.FinancialStatementCreateInput,
        include: Optional[types.FinancialStatementInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.FinancialStatement,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.FinancialStatementCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.FinancialStatement,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.FinancialStatementWhereUniqueInput,
        include: Optional[types.FinancialStatementInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.FinancialStatement,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.FinancialStatementUpdateInput,
        where: types.FinancialStatementWhereUniqueInput,
        include: Optional[types.FinancialStatementInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.FinancialStatement,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.FinancialStatementWhereUniqueInput,
        data: types.FinancialStatementUpsertInput,
        include: Optional[types.FinancialStatementInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.FinancialStatement,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.FinancialStatementUpdateManyMutationInput,
        where: types.FinancialStatementWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.FinancialStatement,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.FinancialStatementWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.FinancialStatement,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class AuditorOpinionBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.AuditorOpinionCreateInput,
        include: Optional[types.AuditorOpinionInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.AuditorOpinion,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.AuditorOpinionCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.AuditorOpinion,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.AuditorOpinionWhereUniqueInput,
        include: Optional[types.AuditorOpinionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.AuditorOpinion,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.AuditorOpinionUpdateInput,
        where: types.AuditorOpinionWhereUniqueInput,
        include: Optional[types.AuditorOpinionInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.AuditorOpinion,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.AuditorOpinionWhereUniqueInput,
        data: types.AuditorOpinionUpsertInput,
        include: Optional[types.AuditorOpinionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.AuditorOpinion,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.AuditorOpinionUpdateManyMutationInput,
        where: types.AuditorOpinionWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.AuditorOpinion,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.AuditorOpinionWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.AuditorOpinion,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class NarrativeRiskAnalysisBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.NarrativeRiskAnalysisCreateInput,
        include: Optional[types.NarrativeRiskAnalysisInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.NarrativeRiskAnalysis,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.NarrativeRiskAnalysisCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.NarrativeRiskAnalysis,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.NarrativeRiskAnalysisWhereUniqueInput,
        include: Optional[types.NarrativeRiskAnalysisInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.NarrativeRiskAnalysis,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.NarrativeRiskAnalysisUpdateInput,
        where: types.NarrativeRiskAnalysisWhereUniqueInput,
        include: Optional[types.NarrativeRiskAnalysisInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.NarrativeRiskAnalysis,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.NarrativeRiskAnalysisWhereUniqueInput,
        data: types.NarrativeRiskAnalysisUpsertInput,
        include: Optional[types.NarrativeRiskAnalysisInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.NarrativeRiskAnalysis,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.NarrativeRiskAnalysisUpdateManyMutationInput,
        where: types.NarrativeRiskAnalysisWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.NarrativeRiskAnalysis,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.NarrativeRiskAnalysisWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.NarrativeRiskAnalysis,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class NotesRiskAnalysisBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.NotesRiskAnalysisCreateInput,
        include: Optional[types.NotesRiskAnalysisInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.NotesRiskAnalysis,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.NotesRiskAnalysisCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.NotesRiskAnalysis,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.NotesRiskAnalysisWhereUniqueInput,
        include: Optional[types.NotesRiskAnalysisInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.NotesRiskAnalysis,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.NotesRiskAnalysisUpdateInput,
        where: types.NotesRiskAnalysisWhereUniqueInput,
        include: Optional[types.NotesRiskAnalysisInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.NotesRiskAnalysis,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.NotesRiskAnalysisWhereUniqueInput,
        data: types.NotesRiskAnalysisUpsertInput,
        include: Optional[types.NotesRiskAnalysisInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.NotesRiskAnalysis,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.NotesRiskAnalysisUpdateManyMutationInput,
        where: types.NotesRiskAnalysisWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.NotesRiskAnalysis,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.NotesRiskAnalysisWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.NotesRiskAnalysis,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class AuditVerdictBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.AuditVerdictCreateInput,
        include: Optional[types.AuditVerdictInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.AuditVerdict,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.AuditVerdictCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.AuditVerdict,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.AuditVerdictWhereUniqueInput,
        include: Optional[types.AuditVerdictInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.AuditVerdict,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.AuditVerdictUpdateInput,
        where: types.AuditVerdictWhereUniqueInput,
        include: Optional[types.AuditVerdictInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.AuditVerdict,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.AuditVerdictWhereUniqueInput,
        data: types.AuditVerdictUpsertInput,
        include: Optional[types.AuditVerdictInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.AuditVerdict,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.AuditVerdictUpdateManyMutationInput,
        where: types.AuditVerdictWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.AuditVerdict,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.AuditVerdictWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.AuditVerdict,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class ScoringSnapshotBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.ScoringSnapshotCreateInput,
        include: Optional[types.ScoringSnapshotInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.ScoringSnapshot,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.ScoringSnapshotCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.ScoringSnapshot,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.ScoringSnapshotWhereUniqueInput,
        include: Optional[types.ScoringSnapshotInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.ScoringSnapshot,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.ScoringSnapshotUpdateInput,
        where: types.ScoringSnapshotWhereUniqueInput,
        include: Optional[types.ScoringSnapshotInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.ScoringSnapshot,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.ScoringSnapshotWhereUniqueInput,
        data: types.ScoringSnapshotUpsertInput,
        include: Optional[types.ScoringSnapshotInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.ScoringSnapshot,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.ScoringSnapshotUpdateManyMutationInput,
        where: types.ScoringSnapshotWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.ScoringSnapshot,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.ScoringSnapshotWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.ScoringSnapshot,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class CreditBatchBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.CreditBatchCreateInput,
        include: Optional[types.CreditBatchInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.CreditBatch,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.CreditBatchCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.CreditBatch,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.CreditBatchWhereUniqueInput,
        include: Optional[types.CreditBatchInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.CreditBatch,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.CreditBatchUpdateInput,
        where: types.CreditBatchWhereUniqueInput,
        include: Optional[types.CreditBatchInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.CreditBatch,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.CreditBatchWhereUniqueInput,
        data: types.CreditBatchUpsertInput,
        include: Optional[types.CreditBatchInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.CreditBatch,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.CreditBatchUpdateManyMutationInput,
        where: types.CreditBatchWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.CreditBatch,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.CreditBatchWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.CreditBatch,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class WalletBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.WalletCreateInput,
        include: Optional[types.WalletInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Wallet,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.WalletCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Wallet,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.WalletWhereUniqueInput,
        include: Optional[types.WalletInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Wallet,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.WalletUpdateInput,
        where: types.WalletWhereUniqueInput,
        include: Optional[types.WalletInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Wallet,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.WalletWhereUniqueInput,
        data: types.WalletUpsertInput,
        include: Optional[types.WalletInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Wallet,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.WalletUpdateManyMutationInput,
        where: types.WalletWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Wallet,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.WalletWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Wallet,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class WalletTransactionBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.WalletTransactionCreateInput,
        include: Optional[types.WalletTransactionInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.WalletTransaction,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.WalletTransactionCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.WalletTransaction,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.WalletTransactionWhereUniqueInput,
        include: Optional[types.WalletTransactionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.WalletTransaction,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.WalletTransactionUpdateInput,
        where: types.WalletTransactionWhereUniqueInput,
        include: Optional[types.WalletTransactionInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.WalletTransaction,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.WalletTransactionWhereUniqueInput,
        data: types.WalletTransactionUpsertInput,
        include: Optional[types.WalletTransactionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.WalletTransaction,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.WalletTransactionUpdateManyMutationInput,
        where: types.WalletTransactionWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.WalletTransaction,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.WalletTransactionWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.WalletTransaction,
            arguments={'where': where},
            root_selection=['count'],
        )



Client = Prisma