# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template enums.py.jinja --
from ._compat import StrEnum


class UserRole(StrEnum):
    LAWYER = 'LAWYER'
    ADMIN = 'ADMIN'

class ReportStatus(StrEnum):
    PENDING = 'PENDING'
    PROCESSING = 'PROCESSING'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'
    PARTIAL = 'PARTIAL'
    CANCELLED = 'CANCELLED'

class TargetType(StrEnum):
    COMPANY = 'COMPANY'

class SourceType(StrEnum):
    ORSR = 'ORSR'
    ZRSR = 'ZRSR'
    RPO = 'RPO'
    RPVS = 'RPVS'
    OBCHODNY_VESTNIK = 'OBCHODNY_VESTNIK'
    INSOLVENCY = 'INSOLVENCY'
    POVERENIA = 'POVERENIA'
    FINANCNA_SPRAVA = 'FINANCNA_SPRAVA'
    SP_DLZNICI = 'SP_DLZNICI'
    VSZP_DLZNICI = 'VSZP_DLZNICI'
    DOVERA_DLZNICI = 'DOVERA_DLZNICI'
    UNION_DLZNICI = 'UNION_DLZNICI'
    CRRS = 'CRRS'
    DISKVALIFIKACIE = 'DISKVALIFIKACIE'
    NCRZP = 'NCRZP'
    NCRD = 'NCRD'
    OCHRANNE_ZNAMKY = 'OCHRANNE_ZNAMKY'
    FS_DANOVE_SUBJEKTY = 'FS_DANOVE_SUBJEKTY'
    FS_DPH_REGISTROVANI = 'FS_DPH_REGISTROVANI'
    FS_DPH_RUSENIE = 'FS_DPH_RUSENIE'
    FS_DPH_VYMAZANI = 'FS_DPH_VYMAZANI'
    FS_DPH_NADMERNY_ODPOCET = 'FS_DPH_NADMERNY_ODPOCET'
    FS_DPH_BANKOVE_UCTY = 'FS_DPH_BANKOVE_UCTY'
    FS_DAN_Z_PRIJMOV = 'FS_DAN_Z_PRIJMOV'
    FS_DAN_PRIJMOV_REG = 'FS_DAN_PRIJMOV_REG'
    REGISTER_UZ = 'REGISTER_UZ'
    CRZ = 'CRZ'
    UVO = 'UVO'
    ROZHODNUTIA = 'ROZHODNUTIA'

class SourceStatus(StrEnum):
    PENDING = 'PENDING'
    SUCCESS = 'SUCCESS'
    FAILED = 'FAILED'
    UNAVAILABLE = 'UNAVAILABLE'

class FeedbackCategory(StrEnum):
    BUG = 'BUG'
    IMPROVEMENT = 'IMPROVEMENT'
    QUESTION = 'QUESTION'
    OTHER = 'OTHER'

class MessageType(StrEnum):
    ANNOUNCEMENT = 'ANNOUNCEMENT'
    REPLY = 'REPLY'
    SYSTEM = 'SYSTEM'
    USER = 'USER'

class TransactionType(StrEnum):
    CHARGE = 'CHARGE'
    TOPUP = 'TOPUP'
    REFUND = 'REFUND'
    REFUND_DEDUCTION = 'REFUND_DEDUCTION'

class TransactionStatus(StrEnum):
    PENDING = 'PENDING'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'

class PaymentProvider(StrEnum):
    STRIPE = 'STRIPE'
    PADDLE = 'PADDLE'
    MANUAL = 'MANUAL'

