from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'User',
    'ReportRequest',
    'ReportSource',
    'VerificationToken',
    'PasswordResetToken',
    'Feedback',
    'UserMessage',
    'AdminAuditLog',
    'WatchedCompany',
    'AlertEvent',
    'AlertDelivery',
    'Company',
    'CompanyPerson',
    'NaceCode',
    'CompanyEvent',
    'VestnikEvent',
    'FinancialStatement',
    'AuditorOpinion',
    'NarrativeRiskAnalysis',
    'NotesRiskAnalysis',
    'AuditVerdict',
    'ScoringSnapshot',
    'CreditBatch',
    'Wallet',
    'WalletTransaction',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'User': {
        'reportRequests': 'ReportRequest',
        'feedback': 'Feedback',
        'wallet': 'Wallet',
        'creditBatches': 'CreditBatch',
        'messages': 'UserMessage',
        'sentMessages': 'UserMessage',
        'auditLogs': 'AdminAuditLog',
        'watchedCompanies': 'WatchedCompany',
        'alertDeliveries': 'AlertDelivery',
    },
    'ReportRequest': {
        'user': 'User',
        'sources': 'ReportSource',
    },
    'ReportSource': {
        'reportRequest': 'ReportRequest',
    },
    'VerificationToken': {
    },
    'PasswordResetToken': {
    },
    'Feedback': {
        'user': 'User',
    },
    'UserMessage': {
        'user': 'User',
        'sender': 'User',
    },
    'AdminAuditLog': {
        'admin': 'User',
    },
    'WatchedCompany': {
        'user': 'User',
    },
    'AlertEvent': {
    },
    'AlertDelivery': {
        'user': 'User',
    },
    'Company': {
        'financialStatements': 'FinancialStatement',
        'vestnikEvents': 'VestnikEvent',
        'companyEvents': 'CompanyEvent',
        'auditVerdict': 'AuditVerdict',
        'scoringSnapshots': 'ScoringSnapshot',
        'companyPersons': 'CompanyPerson',
    },
    'CompanyPerson': {
        'company': 'Company',
    },
    'NaceCode': {
    },
    'CompanyEvent': {
        'company': 'Company',
    },
    'VestnikEvent': {
        'company': 'Company',
    },
    'FinancialStatement': {
        'company': 'Company',
        'auditorOpinion': 'AuditorOpinion',
        'narrativeRisk': 'NarrativeRiskAnalysis',
        'notesRisk': 'NotesRiskAnalysis',
    },
    'AuditorOpinion': {
        'statement': 'FinancialStatement',
    },
    'NarrativeRiskAnalysis': {
        'statement': 'FinancialStatement',
    },
    'NotesRiskAnalysis': {
        'statement': 'FinancialStatement',
    },
    'AuditVerdict': {
        'company': 'Company',
        'snapshots': 'ScoringSnapshot',
    },
    'ScoringSnapshot': {
        'company': 'Company',
        'auditVerdict': 'AuditVerdict',
    },
    'CreditBatch': {
        'user': 'User',
    },
    'Wallet': {
        'user': 'User',
        'transactions': 'WalletTransaction',
    },
    'WalletTransaction': {
        'wallet': 'Wallet',
    },
}

# fmt: on