-- Add new SourceType enum values for 28-registry expansion
ALTER TYPE "SourceType" ADD VALUE IF NOT EXISTS 'RPO';
ALTER TYPE "SourceType" ADD VALUE IF NOT EXISTS 'OBCHODNY_VESTNIK';
ALTER TYPE "SourceType" ADD VALUE IF NOT EXISTS 'CRRS';
ALTER TYPE "SourceType" ADD VALUE IF NOT EXISTS 'OCHRANNE_ZNAMKY';
ALTER TYPE "SourceType" ADD VALUE IF NOT EXISTS 'FS_DPH_BANKOVE_UCTY';
